### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by darcy3812** [darcy3812/Felix-ASP.NET#1]
- [ ] Автоматически выбирать владельца при создании питомца из грида в карточке владельца
- [ ] Исправить заголовки окон
- [ ] не отрабатывает пересчет итоговой стоимости при добавлении/удалении услуг
- [ ] ограничить выбор времени в приемах
- [ ] исправить связанные приемы
- [ ] Анализы
- [ ] Пред. услуги
- [ ] Вакцинания
